name: ws

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  loggy: ^2.0.1+1
  obs_websocket:
    path: ../
  universal_io: ^2.0.4
  web_socket_channel: ^2.2.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
