name: obs_websocket
version: 2.4.1
description: obs_websocket allows dart-based connections to the Open Broadcaster plugin obs-websocket
repository: https://github.com/faithoflifedev/easy_obs_websocket
homepage: https://github.com/faithoflifedev/easy_obs_websocket

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.1
  crypto: ^3.0.2
  json_annotation: ^4.5.0
  universal_io: ^2.0.4
  web_socket_channel: ^2.2.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.1.11
  grinder: ^0.9.1
  json_serializable: ^6.2.0
  lints: ^2.0.0
  mustache_template: ^2.0.0
  process_run: ^0.12.3+2
  test: ^1.21.1

executables:
  obs:
