name: obs_websocket
version: 2.3.0
description: obs_websocket allows dart-based connections to the Open Broadcaster plugin obs-websocket
repository: https://github.com/faithoflifedev/obsWebsocket
homepage: https://github.com/faithoflifedev/obsWebsocket

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  crypto: ^3.0.1
  json_annotation: ^4.4.0
  universal_io: ^2.0.4
  web_socket_channel: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.7
  grinder: ^0.9.0
  json_serializable: ^6.1.4
  lints: ^1.0.1
  mustache_template: ^2.0.0
  process_run: ^0.12.3+2
  test: ^1.20.1
