name: obs_websocket
version: 2.0.5
description: obs_websocket allows dart-based connections to the Open Broadcaster plugin obs-websocket
repository: https://github.com/faithoflifedev/obsWebsocket
homepage: https://github.com/faithoflifedev/obsWebsocket

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  crypto: ^3.0.1
  json_annotation: ^4.0.1
  universal_io: ^2.0.4
  web_socket_channel: ^2.1.0


dev_dependencies:
  build_runner: ^2.0.3
  json_serializable: ^4.1.1
  pedantic: ^1.11.0