name: obs_websocket
version: 5.0.0-dev.1
description: obs_websocket allows dart-based connections to the Open Broadcaster plugin obs-websocket
repository: https://github.com/faithoflifedev/easy_obs_websocket
homepage: https://github.com/faithoflifedev/easy_obs_websocket

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  args: ^2.3.1
  async: ^2.9.0
  crypto: ^3.0.2
  json_annotation: ^4.6.0
  loggy: ^2.0.1+1
  uuid: ^3.0.6
  universal_io: ^2.0.4
  web_socket_channel: ^2.2.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.1.11
  grinder: ^0.9.2
  json_serializable: ^6.3.1
  lints: ^2.0.0
  mustache_template: ^2.0.0
  process_run: ^0.12.3+2
  test: ^1.21.4

executables:
  obs:
