name: obs_websocket
version: 2.0.0
description: obs_websocket allows dart-based connections to the Open Broadcaster plugin obs-websocket
repository: https://github.com/faithoflifedev/obsWebsocket
homepage: https://github.com/faithoflifedev/obsWebsocket

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  web_socket_channel: ^2.0.0
  crypto: ^3.0.1
  json_annotation: ^4.0.1


dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: ^4.1.1