templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 5.0.0-dev.5
change: |
  * obs at the command prompt
  * updated README
  * `obs version` to confirm installed package from cli
