templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 5.0.0
change: |
  * production release
  * obs cli can run shell commands with `listen`
  * improved cli README
