repo: faithoflifedev/obs_websocket
templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 5.0.0+1
change: |
  * support for GetSceneItemIndex and SetSceneItemIndex
  * improved build tools
