templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 2.4.4
change: "fix missing parameter for refreshBrowser https://github.com/faithoflifedev/obs_websocket/pull/15"
