templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 5.0.0-dev.4
change: " - SceneListResponse fix null currentPreviewSceneName
  - batch operations now supported
  - add batch.dart example"
