repo: faithoflifedev/obs_websocket

pkg:
  githubBearerToken: [access token]
  humanName: obs_websocket
  botName: FLN Developer
  botEmail: faithoflifedev@gmail.com
  executables:
    obs: bin/obs.dart
  homebrewRepo: faithoflifedev/homebrew-obs_websocket
  # homebrewFormula: Formula/obs.rb

meta: lib/src/util/meta.dart

templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 5.0.0+3
commit: more config requests, tests and improved build tools
change: |
  * SetPersistentData, GetSceneCollectionList, SetCurrentSceneCollection, CreateSceneCollection, GetProfileList, GetProfileParameter, SetProfileParameter now supported as high level commands
  * more tests
  * improved build tools
